apiVersion: v1
kind: Deployment
metadata:
  name: privnet-sidechain-did-node
  labels:
    app: privnet-sidechain-did-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privnet-sidechain-did-node
  template:
    metadata:
      labels:
        app: privnet-sidechain-did-node
    spec:
      containers:
      - name: privnet-sidechain-did-node
        image: cyberrepublic/elastos-sidechain-did-node:privnet-v0.6
        ports:
        - containerPort: 20604
        - containerPort: 20605
        - containerPort: 20606
        - containerPort: 20607
        - containerPort: 20608
        volumeMounts:
        - mountPath: /did/elastos_did
          name: privnet-sidechain-did-node-hostpath0
        - mountPath: /did/config.json
          name: privnet-sidechain-did-node-hostpath1
      volumes:
      - name: privnet-sidechain-did-node-hostpath0
        hostPath:
          path: /home/rahulguna2/Documents/.volumes/elastos-privnet/did-node
      - name: privnet-sidechain-did-node-hostpath1
        hostPath:
          path: /home/rahulguna2/Documents/elastos-privnet/blockchain/ela-sidechain/did/did-node/config.json
        
