apiVersion: v1
kind: Service
metadata:
  name: privnet-sidechain-did-node
  labels:
    app: privnet-sidechain-did-node
spec:
  ports:
  - name: "20604"
    port: 20604
    targetPort: 20604
  - name: "20605"
    port: 20605
    targetPort: 20605
  - name: "20606"
    port: 20606
    targetPort: 20606
  - name: "20607"
    port: 20607
    targetPort: 20607
  - name: "20608"
    port: 20608
    targetPort: 20608
  selector:
    app: privnet-sidechain-did-node
  type: NodePort
